### PR TITLE
Fix #14: Fixed order of printscreen() and thereIsOneLastSurvivor() functions.

### LINKED ISSUE #14: Second last robot remains on screen after game is finished.
I recommend switching the printscreen() and the thereIsOneLastSurvivor() check around. 
I will fix this. 
Thanks

### PR DESCRIPTION
**Pull request by PopeSpaceous**
Reordered the functions so after the last robot is destroyed only one remains.

### CODE REVIEW

**Comment by cjlcarvalho** [comment]
It is conflicting with your PR solving the crash problem. Can you fix this?

**Comment by PopeSpaceous** [comment]
Sure thing.

**Comment by PopeSpaceous** [comment]
Should be good now. Let me know if you need any other changes to merge it. Thanks

**Comment by cjlcarvalho** [comment]
Now this PR is conflicting with that patch to check condition if all robots are destroyed.

**Comment by PopeSpaceous** [comment]
Hopefully good now. White space conflict.

**Pull request merged**
